{
 "title": "Gatling_2.0",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "db", "query": "influxdb" },
   { "name": "Prefix", "label": "Prefix", "query": "show measurements" },
   {
    "name": "request",
    "label": "request",
    "query": "SHOW TAG VALUES from /^$Prefix$/ WITH KEY = \"request\"  WHERE (\"request\" <> 'allRequests' AND \"request\" <> 'users')"
   }
  ]
 },
 "panels": [
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"waiting\", \"active\", \"done\"  FROM /^$Prefix$/ WHERE (\"request\" = 'users') AND $timeFilter",
     "select": [
      [
       { "params": [ "active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "users" }
     ]
    }
   ]
  },
  {
   "title": "Indicators",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "alias": "t < 800 ms",
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"mean\" <= 800 and \"status\" = 'ok' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "800 ms < t < 1200 ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"mean\" > 800 and \"mean\" <= 1200 and \"status\" = 'ok' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "t > 1200ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"mean\" > 1200 and \"status\" = 'ok' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"status\" = 'ko' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "simulation" ], "type": "tag" },
      { "params": [ "group1" ], "type": "tag" },
      { "params": [ "group2" ], "type": "tag" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \n   sum(\"count\") AS \"Total\",\n   min(\"min\") AS \"Min\", \n   percentile(\"percentiles50\", 50) AS \"50th pct\", \n   percentile(\"percentiles75\", 75) AS \"75th pct\", \n   percentile(\"percentiles95\", 95) AS \"95th pct\", \n   percentile(\"percentiles99\", 99) AS \"99th pct\", \n   max(\"max\") AS \"Max\", \n   mean(\"mean\") AS \"Mean\" \nFROM \n   /^$Prefix$/\nWHERE \n   \"status\" = 'all' AND\n    $timeFilter\nGROUP BY \n   \"request\"\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "OK",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 6 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT sum(\"count\") AS \"OK\" FROM \"$db\" WHERE \"status\" = 'ok' AND  \"simulation\" = '$profile' AND $timeFilter GROUP BY  \"request\" ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "KO",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT sum(\"count\") AS \"OK\" FROM \"$db\" WHERE \"status\" = 'ok' AND  \"simulation\" = '$profile' AND $timeFilter GROUP BY  \"request\" ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "All req",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT last(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (95% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"percentiles95\" FROM \"PTA7\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (99% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"percentiles99\" FROM \"$db\" WHERE (\"request\" <> 'allRequests') AND $timeFilter and \"simulation\" = '$profile' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "All Passes",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"count\" FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "All Errors",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT count FROM /^$Prefix$/ WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ko') and \"simulation\" = '$profile' group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "Pass $tag_request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Error $tag_request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT count/$writeperiod FROM \"$db\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ko') and \"simulation\" = '$profile' group by request",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (50% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"percentiles50\" FROM /^$Prefix$/ WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT mean(\"active\") FROM \"$db.users\" WHERE \"request\" != 'allUsers' AND $timeFilter and \"simulation\" = '$profile' GROUP BY time(1s), \"simulation\" ",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Request details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Individual Requests (95% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "/^$request$/" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"percentiles95\" FROM /^$Prefix$/ WHERE (\"request\" <> 'allRequests' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"/^$request$/\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (99% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "/^$request$/" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"percentiles99\" FROM /^$Prefix$/ WHERE (\"request\" <> 'allRequests' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"/^$request$/\"",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "/^$request$/" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT count/$writeperiod FROM \"$db\" WHERE $timeFilter AND (\"request\" = '${request}' AND \"status\" = 'ok') and \"simulation\" = '$profile' group by request",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "/^$request$/" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT count/$writeperiod FROM \"$db\" WHERE $timeFilter AND (\"request\" = '${request}' AND \"status\" = 'ko') and \"simulation\" = '$profile' group by request",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (50% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "/^$request$/" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT \"percentiles50\" FROM \"$db\" WHERE (\"request\" = '${request}') AND $timeFilter and \"simulation\" = '$profile' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" },
      { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  }
 ]
}